# Define conversation states
MAIN_MENU, HOW_TO_USE, START_VENTING, VENTING, VENT_OPTIONS = range(5)
MY_PROFILE, EDIT_PROFILE, RULES, HELP, ABOUT = range(5, 10)
PROFESSIONAL_SUPPORT, SUPPORT_GROUP, SOS= range(10, 13)
SOS_LOCATION = 31
SOS_VOICE = 32
SOS_PHOTO = 33