# Define conversation states
MAIN_MENU, HOW_TO_USE, START_VENTING, VENTING, VENT_OPTIONS = range(5)
MY_PROFILE, EDIT_PROFILE, RULES, HELP, ABOUT = range(5, 10)
PROFESSIONAL_SUPPORT, SUPPORT_GROUP = range(10, 12)